import Navbars from './Components/Navbar/Navbars';
import { Providers } from './Providers';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbars />
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
